### ISSUE TITLE
百度网盘里的数据集是空的

### ISSUE THREAD

**Issue by sailist** [MANLP-suda/Data-set#1]
可不可以提供一下新的链接 or 更新一下 :)

**Comment by ccac2022ecemc** [comment]
你指的是哪一个数据集。

**Comment by MANLP-suda** [comment]
你指的是哪个数据集

**Comment by sailist** [comment]
我需要 MOSEI 的数据集，你 README.md 里提供的这个链接是空的 
```
The dataset can be download in dataset link：https://pan.baidu.com/s/1tHr--TFISUVz_SOLOjYTxg code：d7su
```

**Comment by MANLP-suda** [comment]
这个数据集来自于，https://github.com/A2Zadeh/CMU-MultimodalSDK。 这上面有提供原始处于和一个处理工具包，简单几步就可以得到这个数据。 unaligned的这个数据集，我这几天找找看有没有备份，百度云数据可能被误删了。如果你着急用的话，或者想了解下怎么获取这个公开数据，你可以尝试下我提供的官网链接，自行获取这个cmu开源数据。
